### ISSUE TITLE
Exception when running lein tar

### ISSUE THREAD

**Issue by macourtney** [technomancy/lein-tar#6]
After adding lein-tar to my plugins and running "lein deps" to download the jars, I get the following exception:

java.lang.RuntimeException: file name 'masques-1.0.0-SNAPSHOT/lib/target/C:/Users/mcourtney/.m2/repository/org/swinglabs/swingx/swingx-painters/1.6.3/swingx-painters-1.6.3.jar' is too long ( > 100 bytes)
        at org.apache.tools.tar.TarOutputStream.putNextEntry(TarOutputStream.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at leiningen.tar$add_file.invoke(tar.clj:27)
        at leiningen.tar$tar$fn__319.invoke(tar.clj:75)
        at leiningen.tar$tar.invoke(tar.clj:71)
        at clojure.lang.Var.invoke(Var.java:415)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.core$apply.invoke(core.clj:603)
        at leiningen.core.main$resolve_task$fn__1606.doInvoke(main.clj:132)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:603)
        at leiningen.core.main$apply_task.invoke(main.clj:167)
        at leiningen.core.main$_main$fn__1665.invoke(main.clj:237)
        at leiningen.core.main$_main.doInvoke(main.clj:221)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:415)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.core$apply.invoke(core.clj:601)
        at clojure.main$main_opt.invoke(main.clj:324)
        at clojure.main$main.doInvoke(main.clj:427)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:423)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)

Note: I'm running this in cygwin on a windows box.

**Comment by joegallo** [comment]
https://github.com/technomancy/lein-tar/pull/7
