### ISSUE TITLE
lein tar does not work for lein 2.1.1

### ISSUE THREAD

**Issue by dakrone** [technomancy/lein-tar#9]
Lein version 2.1.1

```
∴ lein tar
Created /home/hinmanm/safe/tannaim/target/tannaim-0.1.0-SNAPSHOT.jar
java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentArrayMap
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:541)
        at clojure.java.io$fn__8496$G__8491__8501.invoke(io.clj:35)
        at clojure.java.io$file.invoke(io.clj:413)
        at leiningen.tar$add_jars.invoke(tar.clj:76)
        at leiningen.tar$tar.invoke(tar.clj:99)
        at clojure.lang.Var.invoke(Var.java:415)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.core$apply.invoke(core.clj:619)
        at leiningen.core.main$resolve_task$fn__2165.doInvoke(main.clj:186)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:619)
        at leiningen.core.main$apply_task.invoke(main.clj:226)
        at leiningen.core.main$_main$fn__2232.invoke(main.clj:292)
        at leiningen.core.main$_main.doInvoke(main.clj:281)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:415)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.main$main_opt.invoke(main.clj:335)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:423)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
```

project.clj:

``` clojure
(defproject tannaim "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.4.0"]]
  :profiles {:dev {:dependencies [[clj-http-fake "0.4.1"]]}}
  :plugins [[lein-tar "1.1.1"]]
  :resource-paths ["etc"]
  :aot [tannaim.core]
  :main tannaim.core
  :min-lein-version "2.0.0"
  :test-selectors {:default  #(not (:integration %))
                   :integration :integration
                   :all (constantly true)})
```

**Comment by technomancy** [comment]
Fixed in 1.1.2
